Implement URL state
nptscot/nptscot.github.io pull request #151
Opened 2024-03-03 00:08 UTC by mvl22

This set of changes implements URL state (layers enabled and map position) as per #147, by addition of a hash. E.g.:

#/rnet-simplified,wards,holyrood/#11.52/55.9659/-2.9368

Further work to implement parameters within each layer will follow.

2024-03-04 13:59 UTC, Robinlovelace requested changes
So far it gives the hash for the layer shown. No distinction between network types (fast/quiet) which is essential I think so please implement before we merge. 

Filters can be optional if a lot of work.

Good to see URLs like this though, great progress from my tests locally:

```
#/rnet,data_zones/#10.65/55.943/-3.1844
```

2024-03-04 14:05 UTC, mvl22 commented
Filters and network types (basically the same thing, both are sub layer parameters) are future work as I say. I’m not sure yet how long this will take, as things like the sliders and the current HTML structure will need some work.

2024-03-04 15:22 UTC, Robinlovelace commented
OK, will check @anguscalder on this, probably worth merging this intermediate step, not sure about the relative importance of sub-layer params.

2024-03-04 15:23 UTC, Robinlovelace commented
Comments on this @mem48 ? 

Pro is that it's easy to share map with other layers.

Minor con is increase in code complexity and URL length.

+s outweigh -s and we should merge now is my sense.

Great work Martin.

2024-03-07 19:56 UTC, Robinlovelace approved these changes

2024-03-07 19:56 UTC, Robinlovelace commented on index.html
> +			<button class="accordion">Cohesive network</button>
Can you put separate features in separate PRs @mvl22 ?

Seeing as we probably want both of these features (URL state for different layers + this new panel) will merge now in the spirit of 'go fast break stuff' and to see how it looks on the test website.

Let's see how it looks..

2024-03-07 19:56 UTC, merged