cn update
nptscot/nptscot.github.io pull request #235
Opened 2024-08-30 10:11 UTC by wangzhao0217

- **update color band for CN**
- **add funs and update web**
- **update notes**

2024-08-30 11:03 UTC, Robinlovelace commented
Cool, good to see! Will test.

2024-08-30 11:31 UTC, Robinlovelace requested changes
See comments above. Let's wait for @mvl22 to comment when back. In the meantime I'll try to update the datasets in a separate PR.

2024-08-30 11:31 UTC, Robinlovelace commented on index.html
> +					<select id="networkSelector" onchange="updateNetworkSource()">
OK I see the logic here.

2024-08-30 11:31 UTC, Robinlovelace commented on index.html
> +					<select id="networkSelector" onchange="updateNetworkSource()">
I still think we should only have 1 .pmtiles object.

2024-09-09 21:45 UTC, mvl22 commented
I'll review this shortly. It's not really the best way to do this, but I can hopefully make the documentation clearer for this scenario anyway.

PS The layer management stuff is in a bit of a state of flux at present, with the legend stuff not always fully auto-generated from a definition for instance.

> I still think we should only have 1 .pmtiles object.

Yes, there should be a single dataset with different values in it. Is that on its way?

2024-09-10 03:19 UTC, Robinlovelace commented
Let's revive this conversation in after some changes on the backend side. Great job @wangzhao0217 getting your head round the .js code, this PR works, but I think we need to think over the cn implementation, maybe in a call with @mvl22, before updating it.

2024-09-10 03:19 UTC, closed without merging