243 infrastructure types
nptscot/nptscot.github.io pull request #248
Opened 2024-10-18 16:10 UTC by mvl22

2024-10-18 16:33 UTC, Robinlovelace commented
Great stuff, can take a look on locally hosted version if ready to review? Many thanks!

2024-10-18 16:38 UTC, Robinlovelace requested changes
Minor tweaks around capitalisation suggested.

2024-10-18 16:38 UTC, Robinlovelace commented on manual/shareduse.jpg
Is that the best example of shared use footway we have? All the others look good to me.

2024-10-18 16:38 UTC, Robinlovelace commented on manual/index.md
> +		<td>Segregated track (wide)</td>
I could imagine more data-driven ways of doing this, e.g. having the data in a json and the md/html content being generated from that, to avoid duplication of "Segregated Track (wide)" and to prevent inconsistencies like the typo fixed in the suggestion below, but this is OK for now.

```suggestion
		<td>Segregated Track (wide)</td>
```

Please make capitalisation consistent throughout.

2024-10-18 17:16 UTC, mvl22 commented on manual/shareduse.jpg
> Is that the best example of shared use footway we have? All the others look good to me.

It was one at the better end of shared-use. Perhaps you can clarify what you were thinking of.

I chose all the examples from the existing pool already circulated.

2024-10-18 19:11 UTC, Robinlovelace commented on manual/shareduse.jpg
It could be confusing, bike being ridden in carriageway, parked bikes next to path, a bit ambiguous what you should be looking at, right?

2024-10-18 19:12 UTC, Robinlovelace requested changes

2024-10-18 19:12 UTC, Robinlovelace commented on manual/index.md
> +		<td>Off road cycleway</td>
Inconsistent capitalisation?

2024-10-18 19:13 UTC, Robinlovelace commented on manual/index.md
> +		<td>Off road cycleway</td>
And in other labels. I would be happy to change them but not my decision.

2024-10-18 19:27 UTC, mvl22 commented on manual/shareduse.jpg
I'll see if I can find another. Shared-use often doesn't have people using it, and riding on the road instead, because it's often rubbish: that is the reality...

2024-10-18 19:35 UTC, mvl22 commented on manual/shareduse.jpg
How about this one?

https://www.cyclestreets.net/location/92805/

2024-10-18 20:46 UTC, Robinlovelace commented on manual/shareduse.jpg
That looks better:

![image](https://github.com/user-attachments/assets/b7bc8dfd-4776-47b4-9d56-58db28f27140)

2024-10-18 20:56 UTC, Robinlovelace commented
I plan to make a few tweaks then merge this.

2024-10-18 21:01 UTC, Robinlovelace commented
This is how it looks currently:

![image](https://github.com/user-attachments/assets/d5e3cd13-8876-4201-86bf-a9fd45e83b40)

2024-10-18 21:09 UTC, mvl22 commented on manual/shareduse.jpg
OK, have committed that one.

2024-10-18 21:32 UTC, Robinlovelace commented
Almost there on this, planning to remove the "CBD" column and put the info into the description.

2024-10-18 21:40 UTC, Robinlovelace commented
Looking better and more specific and accurate after a few more tweaks:

![image](https://github.com/user-attachments/assets/6668cde4-6836-48b1-8fa4-b0fdaefd64ef)

Ready to go.

2024-10-18 21:41 UTC, Robinlovelace approved these changes
Ready to go, great work Martin, please take a quick peak at my additional tweaks, and merge at your leisure.

2024-10-19 14:14 UTC, merged

2024-10-19 14:14 UTC, mvl22 commented
Looks great, thanks for adding in the commentary.